/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GetContent': ApiRouteHandler<{ contentId: string }, unknown, never>
    'Content': ApiRouteHandler<{ contentIdea: string; contentType: string }, ApiResponse<200, { contentId: string }>, { topic: 'create-content'; data: { contentIdea: string; contentType: string } }>
    'IdeatorAgent': EventHandler<{ contentIdea: string; contentType: string }, { topic: 'build-outline'; data: { contentId: string } }>
    'ContentWriter': EventHandler<{ contentId: string }, never>
    'ContentOutliner': EventHandler<{ contentId: string }, { topic: 'write-content'; data: { contentId: string } }>
  }
}